# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83dd15751bc0011b995100cf765d979fc09d0c5ff7e53ea57a9ee4db12cfed49953227275debddb0159bd6d55821717cea0e34c41e39b698c2c1bb8f43c2127e

test:
  secret_key_base: 71083b6043272c2e67b3b5782d6e25672d08399de0593db58586cdb718768bd6099a5ca71746b3b71c3cacfe51b445ac37b8a0eca8eac7993d0f5d7a1eb46950

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
